apiVersion: v1
kind: Service
metadata:
  name: vur-app-service
spec:
  type: NodePort
  selector:
    app: vur-app #  метка = поду vur-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002 # порт должен быть в диапазоне 30000-32767
