apiVersion: v1
kind: Service
metadata:
  name: vur-app-service
spec:
  type: NodePort
  selector:
    app: vur-app # селектор соответствует меткам подов
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30007 # Опционально. Если не указан, Kubernetes назначит порт автоматически

