apiVersion: v1
kind: Service
metadata:
  name: vur-vue-service
spec:
  type: NodePort
  selector:
    app: vur-app # должно совпадать с меткой пода vur-vue
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001 # порт должен быть в диапазоне 30000-32767
